version: 2
updates:
  # Enable version updates for maven
  - package-ecosystem: "maven"
    # Look for `pom.xml` in the `root` directory
    directory: "/"
    open-pull-requests-limit: 10
    # Check for updates once daily
    schedule:
      interval: "daily"
      
  - package-ecosystem: "maven"
    directory: "/jexxa-blank-archetype/src/main/resources/archetype-resources"
    open-pull-requests-limit: 10
    # Check for updates once daily
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/jlegmed-blank-archetype/src/main/resources/archetype-resources"
    open-pull-requests-limit: 10
    # Check for updates once daily
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/jexxa-blank-archetype/src/main/resources/archetype-resources/.github/workflows"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/jlegmed-blank-archetype/src/main/resources/archetype-resources/.github/workflows"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"